# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ce2b443b5b59ae972ad5bac5b4c93dac44d3b77f9a5807fd59a726c1be7afd5d7f0fc93cc2bcf8c6b1021a457319f79faca404817e412a31977773074572376

test:
  secret_key_base: 377594c3f742157cda500ed3a99c81c97194d63aaeadf24f2f3475918ad9242750b531dffd6b6f9919b1158c2881afa0427afd52cb20309ea42012fe2a5601b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
